version: 2.1

jobs:
  end-to-end:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: "echo Hello, World!"
workflows:
  end-to-end-workflow:
    jobs:
      - end-to-end
