version: 2.1
dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
jobs:
  e2e:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "End-to-End tests"
          command: "npm run e2e"

workflows:
  end-to-end:
    jobs:
      - e2e
