version: 2.1

jobs:
  end-to-end:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: npm install
          command: npm ci
      - run:
          name: chromdriver install
          command: npm install -g chromedriver
      - run:
          name: execute e2e
          command: npm run e2e
workflows:
  end-to-end-workflow:
    jobs:
      - end-to-end
