version: 2.1

jobs:
  e2e:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "End-to-End tests"
          command: "npm run e2e"

workflows:
  say-hello-workflow:
    jobs:
      - e2e
