version: 2.1

jobs:
  e2e:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "End-to-End tests"
          command: "ng e2e"

workflows:
  end-to-end:
    jobs:
      - e2e
