version: 2.1

orbs:
  browser-tools: circleci/browser-tools@x.y
jobs:
  end-to-end:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: npm install
          command: npm ci
      - run:
          name: execute e2e
          command: npm run e2e
workflows:
  end-to-end-workflow:
    jobs:
      - end-to-end
