version: 2.1

jobs:
  end-to-end:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
          name: npm install
          command: npm ci
      - run:
          name: chromedriver install
          command: npm install chromedriver
      - run:
          name: chrome install
          command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - run:
          name: execute e2e
          command: npm run e2e
workflows:
  end-to-end-workflow:
    jobs:
      - end-to-end
