version: 2.1

orbs:
  common: okode/common@2.0.7
  node: circleci/node@4

jobs:
  test:
    parameters:
      project:
        type: string
      skip-tests:
        type: boolean
        default: false
      skip-e2e:
        type: boolean
        default: false
    executor:
      name: common/node
      feature: '-browsers'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Running e2e tests
          command: npm run e2e